# Shared block-list for AI-tool attribution in commit/push text.
#
# Sourced (not executed) by the commit-msg and pre-push hooks, by
# commit-attribution-check.sh, and by the checks.yml CI workflow, so there is a
# single source of truth for the pattern. POSIX sh.
#
# Note: client-side hooks can always be bypassed with `git ... --no-verify`.
# This enforces the project rule (no tool attribution) for normal use; it is a
# guardrail, not a security control.

# Case-insensitive extended regex (ERE). Matches AI tool names plus any
# co-authoring / "generated by" credit and the robot emoji. The robot emoji is
# built from its UTF-8 bytes (printf octal) so this source file stays pure ASCII
# and passes the charset check, while the pattern still matches the literal.
ROBOT_EMOJI=$(printf '\360\237\244\226')
AI_ATTRIBUTION_PATTERN="claude|codex|copilot|chatgpt|gpt-[0-9]|openai|anthropic|gemini|jules|cursor|co-authored-by|generated (with|by)|${ROBOT_EMOJI}"

# Scan text from stdin for the pattern.
#   $1 = human-readable label for the source being scanned.
# On a match: prints offending numbered lines + an explanation to stderr and
# returns 1. Otherwise returns 0.
ai_attribution_scan() {
    label="$1"
    # `|| true`: grep exits 1 when it finds nothing. Callers may run under
    # `set -e` / `-o pipefail` (e.g. a GitHub Actions `run:` block), where a bare
    # grep non-match would abort on clean input. Decide pass/fail by inspecting
    # the captured output instead of grep's exit status.
    matches=$(grep -niE "$AI_ATTRIBUTION_PATTERN" || true)
    if [ -n "$matches" ]; then
        echo "Blocked: $label references an AI tool or co-authoring credit." >&2
        echo "$matches" | sed 's/^/  /' >&2
        echo "Remove the reference before continuing (project rule: no tool attribution)." >&2
        return 1
    fi
    return 0
}
