"""
Generate static HTML site for GitHub Pages.

This script copies template files to the site directory.
Data is loaded dynamically by the JavaScript from JSON files.
"""

import shutil
from pathlib import Path

SITE_DIR = Path(__file__).parent.parent / "site"
TEMPLATE_DIR = Path(__file__).parent / "templates"


def generate_site():
    """Generate the static site by copying templates."""
    
    # Ensure site directories exist
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    (SITE_DIR / "js").mkdir(parents=True, exist_ok=True)
    (SITE_DIR / "css").mkdir(parents=True, exist_ok=True)
    
    # Copy HTML template
    shutil.copy(TEMPLATE_DIR / "index.html", SITE_DIR / "index.html")
    print(f"Copied {SITE_DIR / 'index.html'}")
    
    # Copy JavaScript
    shutil.copy(TEMPLATE_DIR / "app.js", SITE_DIR / "js" / "app.js")
    print(f"Copied {SITE_DIR / 'js' / 'app.js'}")
    
    # Note: CSS is already in site/css/styles.css and managed separately
    print(f"\nSite generated in {SITE_DIR}/")
    print("Data files should be in site/data/ (generated by process_data.py)")


def main():
    """Generate the static site."""
    generate_site()


if __name__ == "__main__":
    main()
